CompanyDiscounts/CompanyDiscount.Web/Areas/Business/Controllers/AddBusinessLocationsController.cs
using System.Linq;
using System.Web.Mvc;
using CompanyDiscount.Web.Areas.Business.Models;
using CompanyDiscounts.Models;
using CompanyDiscounts.Services.Contracts;
using Microsoft.AspNet.Identity;

namespace CompanyDiscount.Web.Areas.Business.Controllers
{
    public class AddBusinessLocationsController : BusinessBaseController
    {
        private static int businessId;
        private readonly IBusinessLocationsServices businessLocations;
        private readonly IBusinessesServices businesses;

        public AddBusinessLocationsController(IBusinessLocationsServices businessLocations, IBusinessesServices businesses)
        {
            this.businessLocations = businessLocations;
            this.businesses = businesses;
        }

        // GET: Business/AddBusinessLocations
        public ActionResult Index()
        {
            string userId = this.User.Identity.GetUserId();
            var currentBusiness = this.businesses.GetAll().FirstOrDefault(b => b.UserId == userId);
            if (currentBusiness != null)
            {
                businessId = currentBusiness.Id;
            }

            return this.View();
        }

        [HttpPost]
        public void Add(PinViewModel[] pins)
        {
            var businessPins = pins;

            foreach (var pin in businessPins)
            {
                var latitude = pin.Latitude;
                var longitude = pin.Longitude;

                var newBusinessLocation = new BusinessLocation()
                {
                    Latitude = latitude,
                    Longitude = longitude,
                    BusinessId = businessId
                };

                this.businessLocations.Create(newBusinessLocation);
            }
        }
    }
}

CompanyDiscounts/CompanyDiscount.Web/Areas/Business/Views/AddBusinessLocations/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Business/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div id="map_canvas" style="width: 640px; height: 480px;">
</div>
<hr/>
<input type="button" id="AddBusinessLocation" value="Add" onclick="add()">
<hr />
@section Scripts {
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript">
        var pins = [];
        $(document).ready(function() {
            initialize();
        });

        function initialize() {
            var mapOptions = {
                center: new google.maps.LatLng(42.696552, 23.32601),
                zoom: 15,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            var map = new google.maps.Map(document.getElementById("map_canvas"),
                mapOptions);

            map.addListener('click', function (e) {
                var pin = { "Latitude": e.latLng.lat(), "Longitude": e.latLng.lng()};
                pins.push(pin);
                placeMarkerAndPanTo(e.latLng, map);
            });

        }

        function placeMarkerAndPanTo(latLng, map) {
            var marker = new google.maps.Marker({
                position: latLng,
                map: map
            });
            map.panTo(latLng);
        }

        function add() {
            console.log(pins);
            @*$.ajax({
                type: "POST",
                data: pins,
                url: '@Url.Action("Add", "AddBusinessLocations")',
                success: function(result) {
                    window.location = '@Url.Action("Index", "BusinessLocations")';
                }
            });*@
            $.post('@Url.Action("Add", "AddBusinessLocations")', { pins: pins }).then(
                window.location = '@Url.Action("Index", "BusinessLocations")'
            );
        }
    </script>
}